### ISSUE TITLE
[Suggestion] Gradle and NDK tool 

### ISSUE THREAD

**Issue by xiaopao2014** [jangrewe/gitlab-ci-android#48]
There is no gradle and NDK tool in dockfile now.
About NDK some apps may needs.
And for  gradle, as i know, even if we don;t install , gradlew would auto install .But it meas every time runs would cause gradle download ,it takes more time to finish 1 build

**Comment by jangrewe** [comment]
Hi @xiaopao2014,
i may decided to include the NDK, but the reason i don't include Gradle is because that changes a lot more frequently, and also because some people may rely on a different Gradle version than the latest.

It seems to me that you are not using caching, or don't use it properly. There are instructions how to set it up so that Gradle will only be downloaded once, as long as you use proper caching.
